### ISSUE TITLE
Create data set for better evaluation of Raphael

### ISSUE THREAD

**Issue by dcorney** [FullFact/health-misinfo-shared#179]
### Context

We've struggled previously with a formal evaluation of Raphael. It would be useful to create a repeatable benchmark against which to compare future innovations.

### Resarch Question(s)

RQ1. What is the current performance of Raphael on a variety of YouTube videos?

Proposed method:
1. Select a number of videos through Raphael:  (e.g. one Barbra O'Neil, one trusted source, plus a few random ones). 
2. Download the transcripts (e.g. using our [AI Tool to create transcripts](https://ai.fullfact.org/youtube-transcript/20107) - Alphalib will then give access to the text)
3. Pass these transcripts through the new genai-health library to extract claims and calculate the score for each claim
4. Downsample these to a manageable number (e.g. no more than 20 per video)

- We will need to limit this to (e.g.) 100-150 claims to limit effort required. But try and make the claims representative of the range of possible outputs. (I.e. some 'bad' claims and some 'good'.)

5. Store the extracted / paraphrased claims and the scores for each claim in a new spreadsheet.
6. Show each claim to several fact checkers and ask: How checkworthy (dangerous? harmful?) is this claim? 
Ask them to use a Likert scale of 1-5 with a range like: "This claim is worth checking"

>                  1: strongly disagree
>                  5: strongly agree

7. Also ask for confidence in prediction ("Other fact checkers would generally agree with my score")

See [details on Likert scales](https://docs.google.com/document/d/1uuG_Gu0fIvYJwcsv1fveesOFsIfAZcetJ1pU_Jt-q3o/edit?tab=t.

```[tasklist]
### Tasks
- [x] Choose a range of videos
- [x] Extract scored claims into spreadsheet
- [x] Get some AI team members to annotate (verify instructions, claims shown etc.)
- [x] Refine choice of videos, claims, instructions etc.
- [x] Get some Editorial team members to annotate
- [ ] Calculate P, R of current model
```

### Notes

With this data, we can compare the two ranked lists (genai-health vs. fact checker):
Apply threshold & calculate P@10, R@10 etc.
Keep the data & compare with new results if we tweak the prompt etc.

**Comment by dcorney** [comment]
Later thought: choosing the videos to annotate is crucial. If we use this data set to evaluate multiple models/prompts and choose the "best" one, we want it to represent the wider space of online videos. But for practical reasons, we're only going to have the resources to annotate 2/3/4 videos.

**Comment by dcorney** [comment]
I've written some [more detailed plans here](https://docs.google.com/document/d/1uuG_Gu0fIvYJwcsv1fveesOFsIfAZcetJ1pU_Jt-q3o/edit?usp=sharing)

**Comment by dcorney** [comment]
Initial list of YouTube videos to process:
    6xbEOIBkvHY - Queen Camilla cancels engagements after falling unwell with chest infection
    o5fOZBo3iWo - 7 Proven Benefits Of Olive Oil 
    MrjIXLQ_OdA - The Fasting Expert: The Truth About Ozempic, These 3 Foods Are Leading To Cancer! -
    pPmNN__GZyM - Bret Weinstein Claims Hamas Attack Connected To COVID
    E2Chww7IpzU - What is ultra-processed food and what does it mean for your health? | BBC News
    da1vvigy5tQ - Reversing Type 2 diabetes starts with ignoring the guidelines | Sarah Hallberg | TEDxPurdueU
    FcFwpY8lvog - 5 SHOCKING Secrets Barbara O'Neill Reveals to Reverse Type 2 Diabetes Naturally!
   KPY6aRlq07Q - 'GDP figures are extremely disappointing', says shadow chancellor (Sky News: not obviously health related)

**Comment by dcorney** [comment]
I'm going to close this as done and will raise a separate issue about using this data set to evaluate Raphael.
